# Generated by Django 5.0.4 on 2024-04-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(default='Petrol', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Gasoline', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=6000),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(default='Toyota', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='Camry', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2015),
        ),
    ]
