# Generated by Django 5.0.4 on 2024-04-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_predictivemaintenance_prediction_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictivemaintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car'),
        ),
    ]
